const SUPABASE_URL="https://fprbzavehflzqcmxvbxx.supabase.co";
const SUPABASE_ANON_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZwcmJ6YXZlaGZsenFjbXh2Ynh4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODQ0MjMxNzEsImV4cCI6MjA5OTk5OTE3MX0.8_D_7kx9f2as46N7ZrNhGZen25e8TGFd2ue5p1TgTvg";
const db=window.supabase.createClient(SUPABASE_URL,SUPABASE_ANON_KEY);
const maps=["Customs","Woods","Factory","Interchange","Reserve","Shoreline","Lighthouse","Streets","Ground Zero","Labs","Random Map"];
const weapons=[{name:"MP-133 Shotgun",min:1,cost:25000,ammo:"12/70 buckshot or slugs",style:"Budget chaos"},{name:"TOZ-106",min:1,cost:12000,ammo:"20/70 buckshot",style:"Punishment pick"},{name:"Mosin Infantry",min:1,cost:45000,ammo:"7.62x54R basic",style:"Classic pain"},{name:"SKS",min:1,cost:35000,ammo:"7.62x39 best available",style:"Early wipe reliable"},{name:"VPO-136",min:1,cost:38000,ammo:"7.62x39 best available",style:"Semi-auto AK"},{name:"Kedr / Klin",min:5,cost:32000,ammo:"9x18 best available",style:"Leg meta gremlin"},{name:"MP5",min:10,cost:65000,ammo:"9x19 best available",style:"Streamer smooth"},{name:"AKS-74U",min:10,cost:55000,ammo:"5.45x39 best available",style:"Compact fighter"},{name:"OP-SKS",min:15,cost:60000,ammo:"7.62x39 best available",style:"Scoped budget hunter"},{name:"AKM",min:15,cost:85000,ammo:"7.62x39 best available",style:"Hard-hitting bruiser"},{name:"M4A1",min:15,cost:95000,ammo:"5.56 best available",style:"NATO classic"},{name:"RFB",min:20,cost:110000,ammo:"7.62x51 best available",style:"Budget NATO puncher"},{name:"G36",min:20,cost:100000,ammo:"5.56 best available",style:"Reliable 5.56"},{name:"MPX",min:23,cost:120000,ammo:"9x19 best available",style:"Fancy SMG"},{name:"SR-2M Veresk",min:26,cost:140000,ammo:"9x21 best available",style:"Boss melter"},{name:"RD-704",min:30,cost:185000,ammo:"7.62x39 best available",style:"AK beast"},{name:"MCX .300 Blackout",min:30,cost:175000,ammo:".300 BLK best available",style:"CajunVeteran special"},{name:"SA-58",min:37,cost:210000,ammo:"7.62x51 best available",style:"Recoil rodeo"},{name:"RSASS",min:42,cost:260000,ammo:"7.62x51 best available",style:"High roller marksman"}];
const armor=[{name:"No armor",min:1,cost:0},{name:"PACA or soft armor",min:1,cost:25000},{name:"Class 3 armor",min:10,cost:45000},{name:"Class 4 armor",min:15,cost:85000},{name:"Class 5 armor",min:30,cost:140000},{name:"Best armor available",min:42,cost:220000}];
const helmets=[{name:"No helmet",min:1,cost:0},{name:"Basic helmet",min:10,cost:25000},{name:"Class 4 helmet",min:15,cost:60000},{name:"Helmet with face shield if available",min:30,cost:120000}];
const rigs=[{name:"Scav vest",cost:10000},{name:"Bank robber rig",cost:15000},{name:"Any small rig",cost:25000},{name:"Any medium rig",cost:35000},{name:"Any armored rig",cost:70000},{name:"Biggest ugly rig in stash",cost:45000}];
const bags=[{name:"No backpack",cost:0},{name:"Sling",cost:8000},{name:"T-Bag",cost:12000},{name:"Day Pack",cost:18000},{name:"Berkut/Scav BP",cost:30000},{name:"Biggest backpack available",cost:65000}];
const challenges=["Must push first gunshot heard","No looting until first kill","One teammate calls all extracts","Boss hunt if boss spawns","Only one mag loaded at a time","Grenades must be thrown dramatically","If SilverFoxJonesy says stairs, squad rotates stairs"];
let state={event:null,profiles:[],players:[],contracts:[],events:[]};let selectedProfileId="";let selectedEventPlayerId="";let channels=[];
function notify(msg){console.error(msg);const box=document.querySelector('.active-view .notice')||adminNotice;if(box)box.innerHTML=`⚠ ${msg}`;}
function pick(a){return a[Math.floor(Math.random()*a.length)]}function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}function cleanCode(v){return String(v||'').trim().toUpperCase().replace(/[^A-Z0-9]/g,'').slice(0,16)}function newCode(){return 'CV'+Math.floor(1000+Math.random()*9000)}function parseRubles(v){return Number(String(v??'').replace(/[^0-9]/g,''))||0}function fmt(n){return `₽ ${new Intl.NumberFormat('en-US').format(Number(n||0))}`}function activePlayers(){return state.players.filter(p=>p.playing!==false)}function allReady(){const a=activePlayers();return a.length>0&&a.every(p=>p.ready&&p.streamer_name&&Number(p.level)>0&&Number(p.rubles)>0)}function options(list,level){return list.filter(x=>(x.min??1)<=level)}function optionsByMoney(list,level,money){return list.filter(x=>(x.min??1)<=level&&x.cost<=money)}function totalKitCost(k){return k.weapon.cost+k.armor.cost+k.helmet.cost+k.rig.cost+k.bag.cost}function buildRandomKit(level){return{weapon:pick(options(weapons,level)),armor:pick(options(armor,level)),helmet:pick(options(helmets,level)),rig:pick(rigs),bag:pick(bags)}}function buildFallbackKit(level,money){const weapon=optionsByMoney(weapons,level,money).sort((a,b)=>a.cost-b.cost)[0];if(!weapon)return null;let rem=money-weapon.cost;const rig=rigs.filter(x=>x.cost<=rem).sort((a,b)=>a.cost-b.cost)[0];if(!rig)return null;rem-=rig.cost;const ap=options(armor,level).filter(x=>x.cost<=rem).sort((a,b)=>a.cost-b.cost)[0]||armor[0];rem-=ap.cost;const hp=options(helmets,level).filter(x=>x.cost<=rem).sort((a,b)=>a.cost-b.cost)[0]||helmets[0];rem-=hp.cost;const bp=bags.filter(x=>x.cost<=rem).sort((a,b)=>a.cost-b.cost)[0]||bags[0];return{weapon,armor:ap,helmet:hp,rig,bag:bp}}function makeLoadout(p){const level=Number(p.level),money=Number(p.rubles);let kit=null;for(let i=0;i<80;i++){const a=buildRandomKit(level);if(totalKitCost(a)<=money){kit=a;break}}if(!kit)kit=buildFallbackKit(level,money);if(!kit)return{event_id:state.event.id,event_player_id:p.id,streamer_name:p.streamer_name,error_message:'Not enough rubles for an affordable weapon and required rig.',level,money};return{event_id:state.event.id,event_player_id:p.id,streamer_name:p.streamer_name,level,money,weapon:kit.weapon.name,ammo:kit.weapon.ammo,weapon_style:kit.weapon.style,armor:kit.armor.name,helmet:kit.helmet.name,rig:kit.rig.name,backpack:kit.bag.name,estimated_cost:totalKitCost(kit),challenge:pick(challenges)}}
async function init(){mapName.innerHTML=maps.map(m=>`<option>${m}</option>`).join('');bind();await loadProfiles();await loadEventsList();go('homeView');const saved=localStorage.getItem('ctc-event-code');if(saved){adminEventCode.value=saved;streamerEventCode.value=saved;dashboardEventCode.value=saved;}}
function bind(){document.querySelectorAll('[data-go]').forEach(b=>b.addEventListener('click',()=>go(b.dataset.go)));loadAdminEventBtn.onclick=()=>loadOrCreateEvent(adminEventCode.value,true);newEventCodeBtn.onclick=()=>{adminEventCode.value=newCode();loadOrCreateEvent(adminEventCode.value,true)};refreshEventsBtn.onclick=loadEventsList;loadStreamerEventBtn.onclick=()=>loadExistingEvent(streamerEventCode.value);loadDashboardBtn.onclick=()=>loadExistingEvent(dashboardEventCode.value);eventName.onchange=saveEvent;mapName.onchange=saveEvent;dayBtn.onclick=()=>{state.event.time_of_day='Day';saveEvent()};nightBtn.onclick=()=>{state.event.time_of_day='Night';saveEvent()};createProfileBtn.onclick=()=>createProfile(newProfileName.value,true);streamerCreateProfileBtn.onclick=()=>createProfile(streamerNewName.value,true);addProfileToEventBtn.onclick=()=>addProfileToEvent(profileSelect.value);joinEventBtn.onclick=()=>addProfileToEvent(streamerProfileSelect.value,true);generateContractsBtn.onclick=generateContracts;copyBtn.onclick=copyResults;streamerProfileSelect.onchange=e=>{selectedProfileId=e.target.value;renderStreamerForm()};streamerLevelInput.onchange=e=>updateSelectedPlayer({level:Number(e.target.value)});streamerRublesInput.onfocus=e=>e.target.value=String(parseRubles(e.target.value)||'');streamerRublesInput.onchange=e=>updateSelectedPlayer({rubles:parseRubles(e.target.value)});submitReadyBtn.onclick=()=>updateSelectedPlayer({ready:true})}
function go(id){document.querySelectorAll('.view').forEach(v=>v.classList.remove('active-view'));document.getElementById(id).classList.add('active-view');renderAll()}
async function loadEventsList(){
  try{
    const [eventsRes, playersRes] = await Promise.all([
      db.from('ctc_events').select('*').order('created_at',{ascending:false}),
      db.from('ctc_event_players').select('event_id')
    ]);
    if(eventsRes.error)throw eventsRes.error;
    if(playersRes.error)throw playersRes.error;
    const counts={};
    (playersRes.data||[]).forEach(p=>{counts[p.event_id]=(counts[p.event_id]||0)+1});
    state.events=(eventsRes.data||[]).map(e=>({...e,streamer_count:counts[e.id]||0}));
    renderEventManager();
  }catch(err){
    notify('Events list could not load. Run the updated SQL. '+(err.message||err));
  }
}

async function loadProfiles(){const {data,error}=await db.from('ctc_streamer_profiles').select('*').order('streamer_name');if(error){notify('Global streamer list could not load. Run the updated SQL. '+error.message);return}state.profiles=data||[];renderProfileLists()}
async function createProfile(name,selectAfter=false){name=(name||'').trim();if(!name){notify('Enter a streamer name first.');return}let {data:existing}=await db.from('ctc_streamer_profiles').select('*').ilike('streamer_name',name).maybeSingle();if(existing){if(selectAfter){selectedProfileId=existing.id;profileSelect.value=existing.id;streamerProfileSelect.value=existing.id}return renderProfileLists()}const {data,error}=await db.from('ctc_streamer_profiles').insert({streamer_name:name,default_level:1,default_rubles:100000}).select().single();if(error){notify('Create streamer failed: '+error.message);return}await loadProfiles();selectedProfileId=data.id;profileSelect.value=data.id;streamerProfileSelect.value=data.id;newProfileName.value='';streamerNewName.value='';renderStreamerForm()}
async function loadOrCreateEvent(rawCode,createIfMissing=false){const code=cleanCode(rawCode);if(!code){notify('Enter an event code first.');return}localStorage.setItem('ctc-event-code',code);let {data:event,error}=await db.from('ctc_events').select('*').eq('event_code',code).maybeSingle();if(error){notify('Event load failed. Run updated SQL. '+error.message);return}if(!event&&createIfMissing){const res=await db.from('ctc_events').insert({event_code:code,event_name:'Friday Night Mayhem',map:'Customs',time_of_day:'Day',status:'open',squad_rule:pick(challenges)}).select().single();if(res.error){notify('Event create failed: '+res.error.message);return}event=res.data}if(!event){notify('Event code not found. Ask Admin to create it first.');return}state.event=event;adminEventCode.value=code;streamerEventCode.value=code;dashboardEventCode.value=code;await refreshEventData();await loadEventsList();subscribe();renderAll()}
async function loadExistingEvent(rawCode){await loadOrCreateEvent(rawCode,false)}
async function refreshEventData(){if(!state.event)return;const [p,c]=await Promise.all([db.from('ctc_event_players').select('*').eq('event_id',state.event.id).order('created_at'),db.from('ctc_contracts').select('*').eq('event_id',state.event.id).order('created_at')]);if(p.error){notify('Event players could not load: '+p.error.message);return}if(c.error){notify('Contracts could not load: '+c.error.message);return}state.players=p.data||[];state.contracts=c.data||[];const found=state.players.find(x=>x.streamer_profile_id===selectedProfileId);selectedEventPlayerId=found?found.id:selectedEventPlayerId}
function subscribe(){channels.forEach(ch=>db.removeChannel(ch));channels=[];if(!state.event)return;channels=[db.channel('players-'+state.event.id).on('postgres_changes',{event:'*',schema:'public',table:'ctc_event_players',filter:`event_id=eq.${state.event.id}`},async()=>{await refreshEventData();renderAll()}).subscribe(),db.channel('contracts-'+state.event.id).on('postgres_changes',{event:'*',schema:'public',table:'ctc_contracts',filter:`event_id=eq.${state.event.id}`},async()=>{await refreshEventData();renderDashboard()}).subscribe()]}
async function saveEvent(){if(!state.event)return;state.event.event_name=eventName.value;state.event.map=mapName.value;const {error}=await db.from('ctc_events').update({event_name:state.event.event_name,map:state.event.map,time_of_day:state.event.time_of_day}).eq('id',state.event.id);if(error)notify('Event save failed: '+error.message);renderAll()}
async function addProfileToEvent(profileId,fromStreamer=false){if(!state.event){notify('Load an event code first.');return}const profile=state.profiles.find(p=>p.id===profileId);if(!profile){notify('Pick or create a streamer name first.');return}let existing=state.players.find(p=>p.streamer_profile_id===profile.id);if(existing){selectedProfileId=profile.id;selectedEventPlayerId=existing.id;renderAll();return}const payload={event_id:state.event.id,streamer_profile_id:profile.id,streamer_name:profile.streamer_name,level:profile.default_level||1,rubles:profile.default_rubles||100000,playing:true,ready:false};const {data,error}=await db.from('ctc_event_players').insert(payload).select().single();if(error){notify('Join event failed: '+error.message);return}selectedProfileId=profile.id;selectedEventPlayerId=data.id;await refreshEventData();await loadEventsList();renderAll();if(fromStreamer)go('streamerView')}
async function updateEventPlayer(id,patch){const {error}=await db.from('ctc_event_players').update(patch).eq('id',id);if(error){notify('Update failed: '+error.message);return}await refreshEventData();renderAll()}
async function updateSelectedPlayer(patch){if(!selectedEventPlayerId){notify('Join the event first.');return}const player=state.players.find(p=>p.id===selectedEventPlayerId);if(player&&patch.level!==undefined||patch.rubles!==undefined){const profPatch={};if(patch.level!==undefined)profPatch.default_level=patch.level;if(patch.rubles!==undefined)profPatch.default_rubles=patch.rubles;db.from('ctc_streamer_profiles').update(profPatch).eq('id',player.streamer_profile_id)}await updateEventPlayer(selectedEventPlayerId,patch)}
async function generateContracts(){if(!allReady()){notify('All playing streamers must be ready first.');return}let res=await db.from('ctc_contracts').delete().eq('event_id',state.event.id);if(res.error){notify('Could not clear old contracts: '+res.error.message);return}const rows=activePlayers().map(makeLoadout);if(rows.length){res=await db.from('ctc_contracts').insert(rows);if(res.error){notify('Could not save contracts: '+res.error.message);return}}res=await db.from('ctc_events').update({last_rolled_at:new Date().toISOString()}).eq('id',state.event.id);await refreshEventData();go('dashboardView')}
async function deleteEvent(eventId,eventCode){
  const ok=confirm(`Delete event ${eventCode}? This removes that event roster and contracts. Global streamer names stay saved.`);
  if(!ok)return;
  const {error}=await db.from('ctc_events').delete().eq('id',eventId);
  if(error){notify('Delete event failed: '+error.message);return;}
  if(state.event&&state.event.id===eventId){state.event=null;state.players=[];state.contracts=[];currentEventCode.textContent='NONE';}
  await loadEventsList();
  renderAll();
}

function renderEventManager(){
  if(typeof eventManagerBody==='undefined')return;
  if(!state.events.length){
    eventManagerBody.innerHTML='<tr><td colspan="5" class="muted">No events created yet.</td></tr>';
    return;
  }
  eventManagerBody.innerHTML=state.events.map(e=>`<tr class="${state.event&&state.event.id===e.id?'active-event-row':''}"><td><strong class="event-code-cell">${esc(e.event_code)}</strong></td><td>${esc(e.event_name||'Friday Night Mayhem')}</td><td>${esc(e.map||'Customs')} · ${esc(e.time_of_day||'Day')}</td><td><span class="pill small-pill">${e.streamer_count||0}</span></td><td class="event-actions-cell"><button class="action-btn" data-load-event="${e.event_code}">Load</button><button class="action-btn danger" data-delete-event="${e.id}" data-code="${esc(e.event_code)}">Delete</button></td></tr>`).join('');
  document.querySelectorAll('[data-load-event]').forEach(b=>b.onclick=()=>loadOrCreateEvent(b.dataset.loadEvent,false));
  document.querySelectorAll('[data-delete-event]').forEach(b=>b.onclick=()=>deleteEvent(b.dataset.deleteEvent,b.dataset.code));
}

function renderAll(){currentEventCode.textContent=state.event?state.event.event_code:'NONE';renderProfileLists();renderEventManager();renderAdmin();renderStreamerForm();renderDashboard()}
function renderProfileLists(){const opts=state.profiles.map(p=>`<option value="${p.id}">${esc(p.streamer_name)}</option>`).join('');profileSelect.innerHTML=opts||'<option value="">No streamers yet</option>';streamerProfileSelect.innerHTML=opts||'<option value="">No streamers yet</option>';if(selectedProfileId){profileSelect.value=selectedProfileId;streamerProfileSelect.value=selectedProfileId}}
function renderAdmin(){if(!state.event){eventPlayersBody.innerHTML='<tr><td colspan="6" class="muted">Load or create an event to manage the roster.</td></tr>';readyPill.textContent='0/0 Ready';generateContractsBtn.disabled=true;return}eventName.value=state.event.event_name||'';mapName.value=state.event.map||'Customs';dayBtn.classList.toggle('active',state.event.time_of_day==='Day');nightBtn.classList.toggle('active',state.event.time_of_day==='Night');const active=activePlayers();readyPill.textContent=`${active.filter(p=>p.ready).length}/${active.length} Ready`;generateContractsBtn.disabled=!allReady();eventPlayersBody.innerHTML=state.players.map(p=>{const out=p.playing===false;return`<tr><td><span class="status-badge ${out?'out':''}">${out?'Not Playing':'Playing'}</span></td><td><div class="streamer-cell"><span class="avatar">${esc((p.streamer_name||'?')[0])}</span><strong>${esc(p.streamer_name)}</strong></div></td><td><input class="row-input" type="number" value="${p.level}" data-level="${p.id}"></td><td><input class="money-input" value="${fmt(p.rubles)}" data-rubles="${p.id}"></td><td>${out?'<span class="not-required">—</span>':`<button class="action-btn" data-ready="${p.id}" data-isready="${p.ready}">${p.ready?'✓ Ready':'Mark Ready'}</button>`}</td><td><button class="action-btn" data-playing="${p.id}" data-current="${p.playing}">${out?'Mark Playing':'Not Playing'}</button></td></tr>`}).join('');document.querySelectorAll('[data-level]').forEach(i=>i.onchange=e=>updateEventPlayer(i.dataset.level,{level:Number(e.target.value)}));document.querySelectorAll('[data-rubles]').forEach(i=>{i.onfocus=e=>e.target.value=String(parseRubles(e.target.value)||'');i.onchange=e=>updateEventPlayer(i.dataset.rubles,{rubles:parseRubles(e.target.value)})});document.querySelectorAll('[data-ready]').forEach(b=>b.onclick=()=>updateEventPlayer(b.dataset.ready,{ready:b.dataset.isready!=='true'}));document.querySelectorAll('[data-playing]').forEach(b=>b.onclick=()=>updateEventPlayer(b.dataset.playing,{playing:b.dataset.current==='false',ready:false}))}
function renderStreamerForm(){streamerEventDisplay.textContent=state.event?state.event.event_code:'NONE';if(!selectedProfileId&&state.profiles[0])selectedProfileId=state.profiles[0].id;const profile=state.profiles.find(p=>p.id===selectedProfileId);const player=state.players.find(p=>p.streamer_profile_id===selectedProfileId);selectedEventPlayerId=player?player.id:'';if(profile){streamerNameInput.value=profile.streamer_name;streamerLevelInput.value=player?player.level:(profile.default_level||1);streamerRublesInput.value=fmt(player?player.rubles:(profile.default_rubles||100000))}streamerStatus.className=`status-card ${player&&player.ready?'ready':''}`;streamerStatus.innerHTML=player?`<strong>${player.ready?'Ready for Contract':'Joined - Not Ready Yet'}</strong><p>${player.playing===false?'Admin has you marked Not Playing for this event.':'Update level/rubles and mark ready.'}</p>`:'<strong>Not Joined Yet</strong><p>Click Join This Event after selecting your name.</p>';submitReadyBtn.disabled=!player||player.playing===false}
function renderDashboard(){if(!state.event){dashTitle.textContent='No Event Loaded';dashboardResults.className='results-empty';dashboardResults.innerHTML='Load an event code to view contracts.';return}dashTitle.textContent=`${state.event.map} - ${state.event.time_of_day} Raid`;squadRule.textContent=`Squad Rule: ${state.event.squad_rule||''}`;rolledAt.textContent=state.event.last_rolled_at?`Last rolled at ${new Date(state.event.last_rolled_at).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}`:'';copyBtn.disabled=state.contracts.length===0;if(!state.contracts.length){dashboardResults.className='results-empty';dashboardResults.innerHTML='No contracts assigned yet.';return}dashboardResults.className='results-grid';dashboardResults.innerHTML=state.contracts.map((r,i)=>r.error_message?`<article class="contract-card"><div class="contract-top"><div><span class="muted one-line">Level ${r.level} · Rubles ${fmt(r.money)}</span><h3>${esc(r.streamer_name)}</h3></div><span class="num">#${i+1}</span></div><div class="weapon"><h4>Cannot Build Contract</h4><p>${esc(r.error_message)}</p></div></article>`:`<article class="contract-card"><div class="contract-top"><div><span class="muted one-line">Level ${r.level} · Rubles ${fmt(r.money)}</span><h3>${esc(r.streamer_name)}</h3></div><span class="num">#${i+1}</span></div><div class="weapon"><span>Assigned Gun</span><h4>${esc(r.weapon)}</h4><p>${esc(r.weapon_style)} · ${esc(r.ammo)}</p><b class="yellow">Mod it however you want, but it must stay this gun.</b></div><div class="gear-grid"><div class="gear"><span>Armor</span><b>${esc(r.armor)}</b></div><div class="gear"><span>Helmet</span><b>${esc(r.helmet)}</b></div><div class="gear"><span>Rig</span><b>${esc(r.rig)}</b></div><div class="gear"><span>Backpack</span><b>${esc(r.backpack)}</b></div></div><div class="cost"><span class="muted">Estimated Kit Cost</span><br><b>${fmt(r.estimated_cost)}</b></div><div class="challenge"><span class="muted">Contract Twist</span><br><b>${esc(r.challenge)}</b></div></article>`).join('')}
function copyResults(){const txt=(state.event?`${state.event.event_name}\nEvent Code: ${state.event.event_code}\n${state.event.map} - ${state.event.time_of_day}\n\n`:'')+state.contracts.map(r=>r.error_message?`${r.streamer_name}: ${r.error_message}`:`${r.streamer_name}\nRubles: ${fmt(r.money)}\nGun: ${r.weapon}\nAmmo: ${r.ammo}\nArmor: ${r.armor}\nHelmet: ${r.helmet}\nRig: ${r.rig}\nBackpack: ${r.backpack}\nEstimated Cost: ${fmt(r.estimated_cost)}\nTwist: ${r.challenge}`).join('\n\n');navigator.clipboard.writeText(txt)}
init();
