const maps=["Customs","Woods","Factory","Interchange","Reserve","Shoreline","Lighthouse","Streets","Ground Zero","Labs","Random Map"];
const weapons=[{name:"MP-133 Shotgun",min:1,cost:25000,ammo:"12/70 buckshot or slugs",style:"Available Rubles chaos"},{name:"TOZ-106",min:1,cost:12000,ammo:"20/70 buckshot",style:"Punishment pick"},{name:"Mosin Infantry",min:1,cost:45000,ammo:"7.62x54R basic",style:"Classic pain"},{name:"SKS",min:1,cost:35000,ammo:"7.62x39 best available",style:"Early wipe reliable"},{name:"VPO-136",min:1,cost:38000,ammo:"7.62x39 best available",style:"Semi-auto AK"},{name:"Kedr / Klin",min:5,cost:32000,ammo:"9x18 best available",style:"Leg meta gremlin"},{name:"MP5",min:10,cost:65000,ammo:"9x19 best available",style:"Streamer smooth"},{name:"AKS-74U",min:10,cost:55000,ammo:"5.45x39 best available",style:"Compact fighter"},{name:"OP-SKS",min:15,cost:60000,ammo:"7.62x39 best available",style:"Scoped budget hunter"},{name:"AKM",min:15,cost:85000,ammo:"7.62x39 best available",style:"Hard-hitting bruiser"},{name:"M4A1",min:15,cost:95000,ammo:"5.56 best available",style:"NATO classic"},{name:"RFB",min:20,cost:110000,ammo:"7.62x51 best available",style:"Available Rubles NATO puncher"},{name:"G36",min:20,cost:100000,ammo:"5.56 best available",style:"Reliable 5.56"},{name:"MPX",min:23,cost:120000,ammo:"9x19 best available",style:"Fancy SMG"},{name:"SR-2M Veresk",min:26,cost:140000,ammo:"9x21 best available",style:"Boss melter"},{name:"RD-704",min:30,cost:185000,ammo:"7.62x39 best available",style:"AK beast"},{name:"MCX .300 Blackout",min:30,cost:175000,ammo:".300 BLK best available",style:"CajunVeteran special"},{name:"SA-58",min:37,cost:210000,ammo:"7.62x51 best available",style:"Recoil rodeo"},{name:"RSASS",min:42,cost:260000,ammo:"7.62x51 best available",style:"High roller marksman"}];
const armor=[{name:"No armor",min:1,cost:0},{name:"PACA or soft armor",min:1,cost:25000},{name:"Class 3 armor",min:10,cost:45000},{name:"Class 4 armor",min:15,cost:85000},{name:"Class 5 armor",min:30,cost:140000},{name:"Best armor available",min:42,cost:220000}];
const helmets=[{name:"No helmet",min:1,cost:0},{name:"Basic helmet",min:10,cost:25000},{name:"Class 4 helmet",min:15,cost:60000},{name:"Helmet with face shield if available",min:30,cost:120000}];
const rigs=[{name:"Scav vest",cost:10000},{name:"Bank robber rig",cost:15000},{name:"Any small rig",cost:25000},{name:"Any armored rig",cost:70000},{name:"Biggest ugly rig in stash",cost:45000}];
const bags=[{name:"No backpack",cost:0},{name:"Sling",cost:8000},{name:"T-Bag",cost:12000},{name:"Day Pack",cost:18000},{name:"Berkut/Scav BP",cost:30000},{name:"Biggest backpack available",cost:65000}];
const challenges=["Must push first gunshot heard","No looting until first kill","One teammate calls all extracts","Boss hunt if boss spawns","Only one mag loaded at a time","Grenades must be thrown dramatically","If SilverFoxJonesy says stairs, squad rotates stairs"];
const defaultState={eventCode:"CV7264",eventName:"Friday Night Mayhem",map:"Customs",time:"Day",players:[{id:crypto.randomUUID(),name:"CajunVeteran",level:42,money:2500000,ready:true,active:true},{id:crypto.randomUUID(),name:"SilverFoxJonesy",level:37,money:1800000,ready:true,active:true},{id:crypto.randomUUID(),name:"WickedWill",level:28,money:1200000,ready:true,active:true},{id:crypto.randomUUID(),name:"BackwoodBeast",level:22,money:900000,ready:true,active:true},{id:crypto.randomUUID(),name:"SwampyFPS",level:31,money:1500000,ready:false,active:false},{id:crypto.randomUUID(),name:"BayouBandit",level:16,money:600000,ready:false,active:false}],results:[],rolledAt:"",squadRule:pick(challenges)};
let state=load();let selectedId=state.players[0]?.id||"";state.players=state.players.map(p=>({...p,active:p.active!==false}));
function load(){try{return JSON.parse(localStorage.getItem('ctc-state'))||defaultState}catch{return defaultState}}function save(){localStorage.setItem('ctc-state',JSON.stringify(state))}function pick(a){return a[Math.floor(Math.random()*a.length)]}function fmt(n){return `₽ ${new Intl.NumberFormat('en-US').format(Number(n||0))}`}function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}function activePlayers(){return state.players.filter(p=>p.active!==false)}function allReady(){const a=activePlayers();return a.length>0&&a.every(p=>p.ready&&p.name&&Number(p.level)>0&&Number(p.money)>0)}
function options(list,level){return list.filter(x=>(x.min??1)<=level)}
function optionsByMoney(list,level,money){return list.filter(x=>(x.min??1)<=level&&x.cost<=money)}
function totalKitCost(kit){return kit.weapon.cost+kit.armor.cost+kit.helmet.cost+kit.rig.cost+kit.bag.cost}
function buildRandomKit(level){
  return {
    weapon:pick(options(weapons,level)),
    armor:pick(options(armor,level)),
    helmet:pick(options(helmets,level)),
    rig:pick(rigs),
    bag:pick(bags)
  };
}
function buildFallbackKit(level,money){
  const weapon=optionsByMoney(weapons,level,money).sort((a,b)=>a.cost-b.cost)[0];
  if(!weapon)return null;
  let remaining=money-weapon.cost;
  const rig=rigs.filter(x=>x.cost<=remaining).sort((a,b)=>a.cost-b.cost)[0];
  if(!rig)return null;
  remaining-=rig.cost;
  const armorPick=options(armor,level).filter(x=>x.cost<=remaining).sort((a,b)=>a.cost-b.cost)[0]||armor[0];
  remaining-=armorPick.cost;
  const helmetPick=options(helmets,level).filter(x=>x.cost<=remaining).sort((a,b)=>a.cost-b.cost)[0]||helmets[0];
  remaining-=helmetPick.cost;
  const bagPick=bags.filter(x=>x.cost<=remaining).sort((a,b)=>a.cost-b.cost)[0]||bags[0];
  return {weapon,armor:armorPick,helmet:helmetPick,rig,bag:bagPick};
}
function makeLoadout(p){
  const level=Number(p.level), money=Number(p.money);
  let kit=null;
  for(let i=0;i<80;i++){
    const attempt=buildRandomKit(level);
    if(totalKitCost(attempt)<=money){kit=attempt;break;}
  }
  if(!kit)kit=buildFallbackKit(level,money);
  if(!kit)return{id:crypto.randomUUID(),error:true,name:p.name,level,money,message:'Not enough available rubles for an affordable weapon and required rig.'};
  const total=totalKitCost(kit);
  return{id:crypto.randomUUID(),name:p.name,level,money,weapon:kit.weapon,armor:kit.armor,helmet:kit.helmet,rig:kit.rig,bag:kit.bag,total,challenge:pick(challenges)}
}
function init(){document.getElementById('mapName').innerHTML=maps.map(m=>`<option>${m}</option>`).join('');bind();renderAll()}function bind(){document.querySelectorAll('[data-view]').forEach(b=>b.addEventListener('click',()=>setView(b.dataset.view)));eventName.oninput=e=>{state.eventName=e.target.value;save()};mapName.onchange=e=>{state.map=e.target.value;renderAll()};dayBtn.onclick=()=>{state.time='Day';renderAll()};nightBtn.onclick=()=>{state.time='Night';renderAll()};addStreamerBtn.onclick=()=>{const p={id:crypto.randomUUID(),name:'New Streamer',level:1,money:100000,ready:false,active:true};state.players.push(p);selectedId=p.id;renderAll()};randomizeBtn.onclick=randomize;dashRerollBtn.onclick=randomize;copyBtn.onclick=copyResults;streamerSelect.onchange=e=>{selectedId=e.target.value;renderStreamer()};streamerNameInput.oninput=e=>updateSelected('name',e.target.value);streamerLevelInput.oninput=e=>updateSelected('level',Number(e.target.value));streamerMoneyInput.oninput=e=>updateSelected('money',Number(e.target.value));submitReadyBtn.onclick=()=>{state.players=state.players.map(p=>p.id===selectedId?{...p,ready:p.active!==false&&Boolean(p.name&&p.level&&p.money)}:p);renderAll()}}
function setView(id){document.querySelectorAll('.view').forEach(v=>v.classList.remove('active-view'));document.getElementById(id).classList.add('active-view');document.querySelectorAll('.nav-btn').forEach(b=>b.classList.toggle('active',b.dataset.view===id));renderAll()}
function updateSelected(field,value){state.players=state.players.map(p=>p.id===selectedId?{...p,[field]:value}:p);save();renderAdminShellOnly()}
function renderAll(){eventName.value=state.eventName;mapName.value=state.map;dayBtn.classList.toggle('active',state.time==='Day');nightBtn.classList.toggle('active',state.time==='Night');eventCodeTop.textContent=state.eventCode;eventCodePlayer.textContent=state.eventCode;renderAdmin();renderStreamer();renderDashboard();save()}
function renderAdminShellOnly(){renderReadyPill();save()}
function renderReadyPill(){const active=activePlayers();const ready=active.filter(p=>p.ready).length;readyPill.textContent=`${ready}/${active.length} Ready`;randomizeBtn.disabled=!allReady();dashRerollBtn.disabled=!allReady();adminNotice.innerHTML=allReady()?`ⓘ All playing streamers are ready. Randomization is unlocked.`:`ⓘ Waiting for all playing streamers to be ready.`}
function renderAdmin(){const playing=activePlayers(),out=state.players.filter(p=>p.active===false);playingBody.innerHTML=playing.map(row).join('');notPlayingBody.innerHTML=out.map(row).join('');notPlayingCount.textContent=out.length;renderReadyPill();document.querySelectorAll('[data-toggle]').forEach(b=>b.onclick=()=>{state.players=state.players.map(p=>p.id===b.dataset.toggle?{...p,active:!(p.active!==false),ready:false}:p);renderAll()});document.querySelectorAll('[data-ready]').forEach(b=>b.onclick=()=>{state.players=state.players.map(p=>p.id===b.dataset.ready&&p.active!==false?{...p,ready:!p.ready}:p);renderAll()});document.querySelectorAll('[data-field]').forEach(i=>i.oninput=e=>{const id=i.dataset.id,field=i.dataset.field,val=field==='name'?e.target.value:Number(e.target.value);state.players=state.players.map(p=>p.id===id?{...p,[field]:val}:p);save();renderReadyPill()})}
function row(p){const out=p.active===false;return`<tr><td><span class="status-badge ${out?'out':''}">${out?'Not Playing':'Playing'}</span></td><td><div class="streamer-cell"><span class="avatar">${esc((p.name||'?')[0])}</span><input class="name-input" data-field="name" data-id="${p.id}" value="${esc(p.name)}"></div></td><td><input class="row-input" type="number" data-field="level" data-id="${p.id}" value="${p.level}"></td><td><input class="money-input" type="number" data-field="money" data-id="${p.id}" value="${p.money}"></td><td>${out?'<span class="not-required">— Not Required</span>':`<button class="action-btn" data-ready="${p.id}">${p.ready?'✓ Ready':'Mark Ready'}</button>`}</td><td><button class="action-btn" data-toggle="${p.id}">${out?'Mark As Playing':'Mark Not Playing'}</button></td></tr>`}
function renderStreamer(){streamerSelect.innerHTML=state.players.map(p=>`<option value="${p.id}" ${p.id===selectedId?'selected':''}>${esc(p.name)}${p.active===false?' - Not Playing':''}</option>`).join('');const p=state.players.find(x=>x.id===selectedId)||state.players[0];if(!p)return;selectedId=p.id;streamerNameInput.value=p.name;streamerLevelInput.value=p.level;streamerMoneyInput.value=p.money;streamerStatus.className=`status-card ${p.active===false?'out':p.ready?'ready':''}`;streamerStatus.innerHTML=`<strong>${p.active===false?'Not Playing This Run':p.ready?'Ready for Contract':'Not Ready Yet'}</strong><p>${p.active===false?'You are still saved in the streamer list, but admin has you sitting out this roll.':'Update your info and submit when ready.'}</p>`;submitReadyBtn.disabled=p.active===false;submitReadyBtn.textContent=p.active===false?'Not Playing This Run':'✓ Submit and Mark Ready'}
function renderDashboard(){dashTitle.textContent=`${state.map} - ${state.time} Raid`;squadRule.textContent=`Squad Rule: ${state.squadRule}`;rolledAt.textContent=state.rolledAt?`Last rolled at ${state.rolledAt}`:'';copyBtn.disabled=state.results.length===0;if(!state.results.length){dashboardResults.className='results-empty';dashboardResults.innerHTML='No contracts assigned yet. Admin must click <b>Randomize Loadouts</b>.';return}dashboardResults.className='results-grid';dashboardResults.innerHTML=state.results.map((r,i)=>r.error?`<article class="contract-card"><div class="contract-top"><div><span class="muted">Level ${r.level} · Available Rubles ${fmt(r.money)}</span><h3>${esc(r.name)}</h3></div><span class="num">#${i+1}</span></div><div class="weapon"><h4>Cannot Build Contract</h4><p>${esc(r.message)}</p></div></article>`:`<article class="contract-card"><div class="contract-top"><div><span class="muted">Level ${r.level} · Available Rubles ${fmt(r.money)}</span><h3>${esc(r.name)}</h3></div><span class="num">#${i+1}</span></div><div class="weapon"><span>Assigned Gun</span><h4>${esc(r.weapon.name)}</h4><p>${esc(r.weapon.style)} · ${esc(r.weapon.ammo)}</p><b class="yellow">Mod it however you want, but it must stay this gun.</b></div><div class="gear-grid"><div class="gear"><span>Armor</span><b>${esc(r.armor.name)}</b></div><div class="gear"><span>Helmet</span><b>${esc(r.helmet.name)}</b></div><div class="gear"><span>Rig</span><b>${esc(r.rig.name)}</b></div><div class="gear"><span>Backpack</span><b>${esc(r.bag.name)}</b></div></div><div class="cost"><span class="muted">Estimated Kit Cost</span><br><b>${fmt(r.total)}</b></div><div class="challenge"><span class="muted">Contract Twist</span><br><b>${esc(r.challenge)}</b></div></article>`).join('')}
function randomize(){if(!allReady())return;state.results=activePlayers().map(makeLoadout);state.rolledAt=new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'});setView('dashboard')}
function copyResults(){const txt=`${state.eventName}\n${state.map} - ${state.time}\n${state.rolledAt}\n\n`+state.results.map(r=>r.error?`${r.name}: ${r.message}`:`${r.name}\nGun: ${r.weapon.name}\nAmmo: ${r.weapon.ammo}\nArmor: ${r.armor.name}\nHelmet: ${r.helmet.name}\nRig: ${r.rig.name}\nBackpack: ${r.bag.name}\nCost: ${fmt(r.total)}\nTwist: ${r.challenge}\nRule: Mod it however you want, but it must stay this gun.`).join('\n\n');navigator.clipboard.writeText(txt)}
init();